name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }} @ ${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      
      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'
      - run: dotnet build tests -c Release

      - run: dotnet test tests -c Release --no-build